[tool.poetry]
name = "ptcs"
version = "0.1.0"
description = ""
authors = ["UTokyo Plarailers <plarailers@gmail.com>"]
readme = "README.md"
packages = [
    { include = "ptcs_control" },
    { include = "ptcs_server" },
]

[tool.poetry.scripts]
server = "ptcs_server.cli:main"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
fastapi = "^0.88.0"
uvicorn = "^0.20.0"
pydantic = "^1.10.2"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
isort = "^5.11.1"
mypy = "^0.991"
pyproject-flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
